name: ldap

services:
  ldap:
    build:
      context: images/${IMAGE_TYPE:-debian}
      dockerfile: Dockerfile
    environment:
      - INIT=${INIT:-false}
      - IMAGE_TYPE
    volumes:
      - "data:/usr/local/var/openldap-data"
      - "./slapd.conf:/usr/local/etc/openldap/slapd.conf:ro"
      - "config:/usr/local/etc/openldap/slapd.d"
    ports:
      - "389:389"
    expose:
      - 389

  ldap_admin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "1080:80"

volumes:
  data:
  config:
